
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.management.StringValueExp;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hell
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        changeLang();
    }

    int currentLang() {
        int langIndex = 1;

        try {

            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM LANGUAGE";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {

                langIndex = rs.getInt(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        return langIndex;
    }

    void changeLang() {
        int langIndex = 1;

        try {

            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM LANGUAGE";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {

                langIndex = rs.getInt(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        switch (langIndex) {
            case 1:
                break;
            case 2:
                jLabel1.setText("Facture");
                jLabel2.setText("ID du patient");
                jLabel3.setText("Nom");
                jLabel5.setText("Le total");
                jButton1.setText("Chercher");
                jButton2.setText("Arrière");
                jButton3.setText("Calculer le total");
                jButton4.setText("Générer une facture");
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel1.setText("Bill");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 70, 26));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("PatientID");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 72, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 120, -1, -1));

        jTextField1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 72, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 120, 221, -1));

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 73, -1, -1));

        jButton2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 503, 80, -1));

        jButton3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Total");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 242, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 242, 191, -1));

        jButton4.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jButton4.setText("Generate Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\main\\java\\Images\\WhiteBack.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String PatientID = jTextField1.getText();
        String Name = null;
        try {
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM PATIENTS";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                boolean flag = false;

                if (rs.getString(1).equals(PatientID)) {
                    flag = true;
                    Name = rs.getString(2);
                    jLabel4.setText(Name);
                }
                if (flag) {
                    break;
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String PatientID = jTextField1.getText();
        Double Total = 0.00;
        Double Cost = null;

        try {
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM TREATMENTS";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {

                if (rs.getString(2).equals(PatientID)) {
                    Cost = rs.getDouble(4);
                    Total += Cost;
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        jLabel6.setText(String.valueOf(Total));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ID = jTextField1.getText();
        String Path = null;
        int go = 0;

        String Transactions = "";

        try {
            Path = "C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\Textfiles\\" + ID + ".txt";
            File file = new File(Path);
            /*If file gets created then the createNewFile() 
	      * method would return true or if the file is 
	      * already present it would return false
             */
            boolean fvar = file.createNewFile();
            
            if (fvar) {
                go = 1;

                switch (currentLang()) {
                    case 1:
                        JOptionPane.showMessageDialog(rootPane, "Bill has been created");
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(rootPane, "Le projet de loi a été créé");
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Bill has been created");
                        break;
                }
            } else {

                int a = 1;
                switch (currentLang()) {
                    case 1:
                        a = JOptionPane.showConfirmDialog(null, "Bill already exists, do you wish to replace with an updated version?", "Existing Bill", JOptionPane.YES_NO_OPTION);
                        break;
                    case 2:
                        a = JOptionPane.showConfirmDialog(null, "Le projet de loi existe déjà, souhaitez-vous le remplacer par une version mise à jour?", "Projet de loi existant", JOptionPane.YES_NO_OPTION);
                        break;
                    default:
                        a = JOptionPane.showConfirmDialog(null, "Bill already exists, do you wish to replace with an updated version?", "Existing Bill", JOptionPane.YES_NO_OPTION);
                        break;
                }

                if (a == 0) {
                    file.delete();
                    
                    boolean fvar2 = file.createNewFile();
                    
                    if (fvar2) {
                        go = 1;

                        switch (currentLang()) {
                            case 1:
                                JOptionPane.showMessageDialog(rootPane, "Bill has been created");
                                break;
                            case 2:
                                JOptionPane.showMessageDialog(rootPane, "Le projet de loi a été créé");
                                break;
                            default:
                                JOptionPane.showMessageDialog(rootPane, "Bill has been created");
                                break;
                        }
                    }
                }

            }
        } catch (IOException e) {
            System.out.println("Exception Occurred:");
            e.printStackTrace();
        }

        if (go == 1) {

            try {
                Connection con = new DBConnect().Connect();
                Statement stmt = con.createStatement();
                String sql = "INSERT INTO BILLS VALUES ('" + ID + "','" + Path + "')";
                stmt.executeUpdate(sql);

            } catch (Exception e) {
                System.out.println(e);
            }

            try {
                Connection con = new DBConnect().Connect();
                Statement stmt = con.createStatement();
                String sql = "SELECT * FROM TREATMENTS";
                ResultSet rs = stmt.executeQuery(sql);

                while (rs.next()) {

                    if (rs.getString(2).equals(ID)) {
                        Transactions += "\nTreatmentNo : " + rs.getString(1) + "\nTreatment : " + rs.getString(3) + "\nCost : Rs." + String.valueOf(rs.getDouble(4)) + "\nDate : " + rs.getString(5) + "\nTime : " + rs.getString(6) + "\n";

                    }
                }

            } catch (Exception e) {
                System.out.println(e);
            }

            String text = "Patient ID : " + jTextField1.getText() + "\n" + "Name : " + jLabel4.getText() + "\n" + Transactions + "\n" + "Total = Rs." + jLabel6.getText() + "\n";
            try {
                FileWriter fw = new FileWriter(Path, true);
                fw.write(text);
                fw.close();
            } catch (IOException e) {
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
