
import java.awt.event.ActionEvent;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        showTime();
        showDate();
    }

    void showTime() {
        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
            timeDis.setText(s.format(d));
        }).start();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dateDis.setText(s.format(d));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateDis = new javax.swing.JLabel();
        timeDis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setUndecorated(true);
        setSize(new java.awt.Dimension(10, 10));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("UserName");
        jLabel1.setPreferredSize(new java.awt.Dimension(65, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 84, -1));

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setText("Close");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 250, -1));

        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 250, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(65, 22));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        dateDis.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        dateDis.setText("jLabel4");
        dateDis.setPreferredSize(new java.awt.Dimension(75, 13));
        getContentPane().add(dateDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, -1, -1));

        timeDis.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        timeDis.setText("jLabel5");
        timeDis.setPreferredSize(new java.awt.Dimension(75, 13));
        getContentPane().add(timeDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\main\\java\\Images\\Login Background.jpg")); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Please Confirm to Exit HMS", "Close", JOptionPane.YES_NO_OPTION);
        if (a == 0)
            System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String un = jTextField1.getText();
        String pwd = jPasswordField1.getText();
        String err = "";

        if (un.equals("Admin")) {

            if (pwd.equals("MasterKey")) {

                String text = "User : Admin \nDate : " + dateDis.getText() + "\nTime : " + timeDis.getText() + "\n\n********************\n\n";
                String Path = "C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\Textfiles\\Login_Log.txt";

                try {

                    FileWriter fw = new FileWriter(Path, true);
                    fw.write(text);
                    fw.close();

                } catch (Exception e) {
                    System.out.println(e);
                }

                new AdminMenu().setVisible(true);
                this.setVisible(false);

            } else {

                JOptionPane.showMessageDialog(null, "Invalid Password");

            }

        } else {

            try {
                Connection con = new DBConnect().Connect();
                Statement stmt = con.createStatement();
                String sql = "SELECT * FROM LOGIN";
                ResultSet rs = stmt.executeQuery(sql);

                while (rs.next()) {
                    String u = rs.getString(1);
                    String p = rs.getString(2);
                    boolean flag = false;

                    if (un.equalsIgnoreCase(u)) {
                        if (pwd.equals(p)) {
                            flag = true;
                            
                            String Path = "C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\Textfiles\\Login_Log.txt";
                            String text = "User : " + un + "\nDate : " + dateDis.getText() + "\nTime : " + timeDis.getText() + "\n\n********************\n\n";
                            
                            try {

                                FileWriter fw = new FileWriter(Path, true);
                                fw.write(text);
                                fw.close();

                            } catch (Exception e) {
                                System.out.println(e);
                            }

                            new Home().setVisible(true);
                            this.setVisible(false);
                            err = "Login Successful";
                        }
                    }
                    if (flag) {
                        break;
                    } else {
                        err = "Invalid Credentials";
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            JOptionPane.showMessageDialog(null, err);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateDis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel timeDis;
    // End of variables declaration//GEN-END:variables
}
