
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hell
 */
public class Records extends javax.swing.JFrame {

    /**
     * Creates new form Records
     */
    public Records() {
        initComponents();
        jTextField8.setEditable(false);
        setPatientID();
        changeLang();
    }
    
    int currentLang(){
        int langIndex = 1;
        
        try {
            
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM LANGUAGE";
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                
                langIndex = rs.getInt(1);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
        return langIndex;
    }
    
    void changeLang() {
        int langIndex = 1;
        
        try {
            
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM LANGUAGE";
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                
                langIndex = rs.getInt(1);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
        switch(langIndex){
            case 1:
                break;
            case 2:
                jLabel1.setText("Nom");
                jLabel2.setText("Le sexe");
                jLabel3.setText("Date de naissance");
                jLabel4.setText("Groupe sanguin");
                jLabel5.setText("Adresse");
                jLabel6.setText("Numéro de contact");
                jLabel7.setText("Email");
                jLabel8.setText("ID du patient");
                jButton1.setText("Fermer");
                jButton2.setText("Ajouter");
            default:
                break;
        }
    }
    
    void setPatientID() {
        long HighestID = 0;
        long CurrentID = 0;
        
        try {
            
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM PATIENTS";
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                
                CurrentID = Long.valueOf(rs.getString(1));
                
                if (HighestID <= CurrentID) {
                    HighestID = CurrentID + 1;
                }
                
                jTextField8.setText("000" + String.valueOf(HighestID));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 467, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 52, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel2.setText("Gender");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 101, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel3.setText("DOB");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel4.setText("Blood Type");
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 199, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel5.setText("Address");
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 248, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel6.setText("Contact No");
        jLabel6.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 297, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel7.setText("Email");
        jLabel7.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 346, -1, -1));

        jTextField1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 53, 500, -1));

        jTextField3.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField3.setText("DD/MM/YYYY");
        jTextField3.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 151, 500, -1));

        jTextField4.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 500, -1));

        jTextField5.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(400, 30));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 249, 500, -1));

        jTextField6.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField6.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 347, 500, -1));

        jTextField7.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField7.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 298, 500, -1));

        jComboBox1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(500, 30));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 102, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel8.setText("Patient ID");
        jLabel8.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 395, -1, -1));

        jTextField8.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField8.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 396, 500, -1));

        jButton2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton2.setText("Add Patient");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 467, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\dinur\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\main\\java\\Images\\WhiteBack.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Name = jTextField1.getText();
        String Gender = (String) jComboBox1.getSelectedItem();
        String DOB = jTextField3.getText();
        String BloodType = jTextField4.getText();
        String Address = jTextField5.getText();
        String ContactNo = jTextField7.getText();
        String Email = jTextField6.getText();
        String PatientID = jTextField8.getText();

        try {
            Connection con = new DBConnect().Connect();
            Statement stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO PATIENTS VALUES ('" + PatientID + "', '" + Name + "', '" + Gender + "', '" + DOB + "', '" + BloodType + "', '" + Address +"', '" + ContactNo + "', '" + Email + "')");
            switch(currentLang()){
                case 1:
                    JOptionPane.showMessageDialog(rootPane, "Patient Added");
                    break;
                case 2:
                    JOptionPane.showMessageDialog(rootPane, "Patient ajouté");
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "Patient Added");
                    break;
            }

            setVisible(false);
            new Home().setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
